### ISSUE TITLE
JSON Object Serialization Problems

### ISSUE THREAD

**Issue by GStefanowich** [dcdeepesh/DiscordIPC#1]
Just wanted to let you know that I came across some typos in your Objects that are used for JSON Serialization while working on a Fork, so you can update them in your code if you want. Since being incorrectly spelled lead to deserialization issues

- [state_instances](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Entities/Guild.cs#L53) in `Guild` should be `stage_instances`
- [rpc_origings](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Entities/Application.cs#L10) in `Application` should be `rpc_origins`
- [user_limite](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Commands/GetChannel.cs#L18) in `GetChannel` should be `user_limit`
- [channe_id](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Events/NotificationCreate.cs#L9) in `NotificationCreate` should be `channel_id`

Great work on the library

**Comment by dcdeepesh** [comment]
Hello Greg,

Good catch on the typos. Since the repository has been dormant for some time now, I'll be bringing it under maintenance again in a day or two, fixing the typos and updating types according to the (hopefully updated) RPC documentation. Contributions are welcome.

Thank you!

**Comment by dcdeepesh** [comment]
Commit d4eeaad0ad6ff281985ef381f1cd625da431a294 fixes this issue.
