### ISSUE TITLE
Spinning up a lot of Tasks

### ISSUE THREAD

**Issue by GStefanowich** [dcdeepesh/DiscordIPC#2]
I'm currently working on a reconnect loop for the `NamedPipeClientStream` and realized that the way you're `.Read()`ing from it is creating a lot of Tasks that maxes out the CPU.

After a successful connect with the pipe you start an infinite loop on a separate Thread and then offload the message handling to a task to continue the loop immediately. The `.Read()` [method blocks](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Core/MessageReadLoop.cs#L62-L67) correctly, _unless the Pipe has reached it's "end"_, in which it **does not** block.

If you open discord, and the pipe connects, and then close discord while the app is still running, the pipe reaches it's "end", causing the read to stop blocking. Since `.Read()` is no longer blocking, [Task.Run()](https://github.com/dcdeepesh/DiscordIPC/blob/8a536a992877c9096ec395e35c2c60dfd3411029/Core/MessageReadLoop.cs#L70-L82) begins to run _indefinitely_ in a `while (true)`

```C#
while (true) {
    /* // This is no longer blocking since the pipe has ended
     * pipe.Read(bOpCode, 0, 4);
     * OpCode opCode = (OpCode) BitConverter.ToInt32(bOpCode, 0);
     * pipe.Read(bLen, 0, 4);
     * int len = BitConverter.ToInt32(bLen, 0);
     * byte[] data = new byte[len];
     * pipe.Read(data, 0, len);
     * message = new IPCMessage(opCode, data);
     */
    
    // This starts running indefinitely
    Task.Run(() => {
        Util.Log("\nRECEIVIED:\n{0}", message.Json);
        var jsonRoot = JsonDocument.Parse(message.Json).RootElement;
        string cmd = jsonRoot.GetProperty("cmd").GetString();
        string evt = "";
        if (jsonRoot.TryGetProperty("evt", out JsonElement elem))
            evt = elem.GetString();
        
        if (cmd == "DISPATCH")
            ipcInstance.FireEvent(evt, message);
        else
            SignalNewResponse(message);
    });
}
```

**Comment by dcdeepesh** [comment]
Fixed in 91ea631b7b9afe433e3a7e81cd9bbcb8c975a683. The read loop now terminates when the pipe is closed or no data is expected.
