### ISSUE TITLE
getAccessTokenFromAuthCode?

### ISSUE THREAD

**Issue by dichternebel** [dcdeepesh/DiscordIPC#4]
Hi,

trying to use your thing because it seems promising.
However, I'm stuck  early... Your documentation uses a method called "getAccessTokenFromAuthCode".
What is that?
Do I have to implement that on my own and if so, what should be done?

**Comment by dcdeepesh** [comment]
Hey,

Yes, the method `getAccessTokenFromAuthCode` is a made up method that is supposed to exchange the auth code returned by the IPC for an access token. That is how OAuth works.
To know how to do it, you must first understand how OAuth2.0 works. Easily available information online (hint: OAuth2.0 supports multiple "flows", the flow you're looking for is called the authorization code flow). Then you need to apply that knowledge to Discord APIs. The [documentation](https://discord.com/developers/docs/topics/oauth2) explains the specifics for Discord.

**Comment by dichternebel** [comment]
Just wanted to say: DiscordIPC works like a charm!
Thanks a lot for sharing!

**Comment by dcdeepesh** [comment]
Thank you for the feedback! Glad to know it's working well. There may or may not be a useful Discord related desktop app coming soon that uses DiscordIPC under the hood ;).
